// AUTO-GENERIERT von web/scripts/generate-whatsnew.mjs — NICHT von Hand bearbeiten.
// Quelle: CHANGELOG.md (Abschnitt "## [v1.9.1]") + src/lib/whatsnew.en.json.
// Neu erzeugen: sh scripts/generate-whatsnew.sh (Release-Ritual).
export type WhatsNewRisk = "gefahrlos" | "backup" | "breaking" | null;

export const WHATS_NEW: { version: string; title: string; titleEn: string; risk: WhatsNewRisk; de: string; en: string } = {
  version: "1.9.1",
  title: "Sicherheits-Auffrischung",
  titleEn: "Security refresh",
  risk: "gefahrlos",
  de: "Keine Migration, keine neuen Funktionen — diese Version schließt Sicherheitslücken in den verwendeten Fremdbibliotheken und macht den Bild-Dienst dicht. Nach dem Deploy sieht die App genauso aus wie vorher.\n\n• Next.js von 14.2.5 auf 14.2.35. Damit sind 12 gemeldete Schwachstellen der eingesetzten Version geschlossen, darunter eine als kritisch eingestufte (Umgehung der Zugangsprüfung in der Middleware). Für unsere Installation war sie nicht erreichbar — wir benutzen keine Middleware —, aber sie stand in der ausgelieferten Bibliothek.\n• Der Bild-Dienst nimmt nur noch die eigenen Bildquellen an. Bisher durfte über die App jede beliebige Bild-Adresse geladen werden (/_next/image akzeptierte jeden fremden Server) — die Installation war damit ein offener Bild-Weiterleiter für Dritte im Netz. Jetzt sind nur noch die vier tatsächlich genutzten Quellen erlaubt: TCGdex, TCGplayer, die Pokédex-Platzhalter und der eigene Server. Alle Bilder in der App laden unverändert (152 Musterprüfungen über acht Umgebungen, dazu 13 Proben am laufenden Dienst).\n• Pillow von 10.4.0 auf 12.3.0 (Bildverarbeitung im Backend). Die Ausgaben sind Byte für Byte identisch zur Vorversion — geprüft über 307 Vergleichspfade mit 47 Eingaben, einschließlich absichtlich kaputter Dateien. Einziger Unterschied: 16-Bit-Graustufen-PNGs werden beim Hochladen jetzt angenommen statt abgelehnt.\n\n• Eine falsch geschriebene Server-Adresse in der Konfiguration (ein überzähliger Schrägstrich am Ende) hätte alle eigenen Kartenfotos unsichtbar gemacht — das wird jetzt abgefangen.\n• Im Menü am Handy landete der Tastatur-Fokus nach dem Schließen unter Umständen nicht mehr auf der Menü-Schaltfläche.",
  en: "No migration, no new features - this release closes security gaps in third-party libraries and locks down the image service. After deploying, the app looks exactly the same as before.\n\n• Next.js updated from 14.2.5 to 14.2.35, closing 12 reported vulnerabilities in the previous version, including one rated critical (an authorization bypass in the middleware). It wasn't reachable in our setup - we don't use middleware - but it shipped in the library we used.\n• The image service now only accepts our own image sources. Previously it could load any image URL (a potential open relay for third parties); now only the four sources we actually use are allowed: TCGdex, TCGplayer, the Pokedex placeholders and our own server. Every image in the app still loads unchanged.\n• Pillow updated from 10.4.0 to 12.3.0 (backend image processing) - output is byte-for-byte identical to the previous version. The only difference: 16-bit grayscale PNGs are now accepted on upload instead of rejected.\n\n• A misconfigured server address (one trailing slash too many) could have made all of your own card photos invisible - this is now caught before it happens.\n• On mobile, closing the menu could leave the keyboard focus off the menu button.",
};
