// AUTO-GENERIERT von web/scripts/generate-whatsnew.mjs — NICHT von Hand bearbeiten.
// Quelle: CHANGELOG.md (Abschnitt "## [v1.9.2]") + src/lib/whatsnew.en.json.
// Neu erzeugen: sh scripts/generate-whatsnew.sh (Release-Ritual).
export type WhatsNewRisk = "gefahrlos" | "backup" | "breaking" | null;

export const WHATS_NEW: { version: string; title: string; titleEn: string; risk: WhatsNewRisk; de: string; en: string } = {
  version: "1.9.2",
  title: "Was ist neu-Box, echte Bild-Optimierung",
  titleEn: "What's-new box, real image optimization",
  risk: "gefahrlos",
  de: "Keine Migration, keine Änderung an deinen Daten. Sichtbar ist vor allem eines: Nach diesem Update begrüßt dich die App einmalig mit einer Box, die sagt, was sich geändert hat. Genau diese hier.\n\n• Nach einem Update zeigt die App einmalig, was sich geändert hat — eine Box mit dem Text aus diesem CHANGELOG und der Risiko-Stufe der Version, in Deutsch oder Englisch je nach eingestellter Sprache. Wegklickbar, danach über die Versionsnummer in den Einstellungen jederzeit wieder erreichbar. Wer die App zum allerersten Mal öffnet, sieht sie nicht — für eine neue Installation ist ohnehin alles neu.\n\n• Der Bild-Zwischenspeicher hat jetzt eine harte Obergrenze (#98, Panel-Nacharbeit). Next.js räumt diesen Speicher von sich aus nie auf: keine Verfallsgrenze, keine Größengrenze. Da der Bild-Dienst ohne Anmeldung erreichbar ist, konnte damit jede:r im Netz unbegrenzt Plattenplatz belegen — auf einem geteilten Server hätte eine volle Platte auch fremde Dienste getroffen. Zwei unabhängige Bremsen: Der Speicher liegt jetzt in einem auf 256 MB fest gedeckelten Arbeitsspeicher-Bereich (die Platte wird gar nicht mehr berührt), und dieselbe Bilddatei lässt sich nicht mehr über angehängte Fragezeichen-Parameter beliebig oft neu ablegen. Gemessen: 5 Abrufe desselben Bildes mit unterschiedlichen Parametern erzeugten vorher 5 zusätzliche Einträge. Keine einzige der 37 372 echten Bild-Adressen im Bestand trägt einen solchen Parameter — für die App ändert sich nichts.",
  en: "No migration, no change to your data. The most visible part: after this update the app greets you once with a box telling you what changed — this one.\n\n• New: after every update the app shows once what changed, taken straight from the changelog, with the version's risk level, in German or English depending on your language setting. Dismiss it and it stays gone; you can reopen it any time from the version number in Settings. A brand-new installation doesn't see it — for a fresh install everything is new anyway.\n• Images are now really optimized. The web container was missing the image library and could not write its cache, so every picture was served unoptimized and re-processed on every request. Both are fixed: pictures come from the cache from the second request on, and the transferred size dropped from about 94 KB to about 26 KB in our measurement.\n• Security: the image cache now has a hard size limit. Next.js never cleans this cache up on its own — no expiry, no size limit — and the image service is reachable without login, so anyone on the network could have filled the disk. On a shared server a full disk would have hit other services too. Two independent brakes now: the cache lives in a memory area capped at 256 MB (the disk is no longer touched at all), and the same image can no longer be stored over and over via appended query parameters.\n• Maintenance: database and frontend libraries refreshed (SQLAlchemy 2.0.52, TypeScript 5.9, Tailwind 3.4.19 and five more). Nothing changes for you — the money calculations were verified to return byte-for-byte the same results.",
};
